B/#203
techeer-sv/graphy pull request #205
Opened 2023-09-20 16:10 UTC by kimhalin

## 🛠️ 변경사항

</br>
</br>

## ☝️ 유의사항

</br>
</br>

## 👀 참고자료

</br>
</br>

## ❗체크리스트
- [ ] 하나의 메소드는 최소의 기능만 하도록 설정했나요?
- [ ] 수정 가능하도록 유연하게 작성했나요?
- [ ] 필요 없는 import문이나 setter 등을 삭제했나요?
- [ ] 기존의 코드에 영향이 없는 것을 확인하였나요?

2023-09-20 16:53 UTC, youKeon requested changes
확인했습니다! 너무 고생 많으셨어요🙃🙃
리뷰 확인 부탁드립니다!!

2023-09-20 16:53 UTC, youKeon commented on backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
>      private static String baseUrl = "/api/v1/follow";
AuthControllerTest랑 CommentControllerTest에는 `BASE_URL`로 되어 있는데 어떤 걸로 통일할까요?!

2023-09-20 16:53 UTC, youKeon commented on backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
> +//    @Test
아래 테스트 코드들은 작성 예정이신 건가요?!

2023-09-20 16:53 UTC, youKeon commented on backend/src/test/java/com/graphy/backend/domain/project/controller/ProjectControllerTest.java
>          String body = objectMapper.writeValueAsString(request);
`PageRequest pageRequest = new PageRequest();`
`String body = objectMapper.writeValueAsString(request);`

두 변수 없어도 테스트 통과합니다!

2023-09-20 16:53 UTC, youKeon commented on backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
> +    void updateProject() throws Exception {
```
        UpdateProjectResponse response = UpdateProjectResponse.builder()
                .projectName(request.getProjectName())
                .description(request.getDescription())
                .thumbNail(request.getThumbNail())
                .content(request.getContent())
                .techTags(request.getTechTags())
                .build();

        Tags tags = new Tags(Arrays.asList(tag1, tag2));
```

미사용 변수입니다!

2023-09-20 16:53 UTC, youKeon commented on backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
> +        assertThat(result.getProjectName()).isEqualTo(project.getProjectName());
`usingRecursiveComparison()` 사용하면 모든 속성 비교 가능합니다!

ex)
`assertThat(result).usingRecursiveComparison().isEqualTo(project);`

2023-09-20 16:53 UTC, youKeon commented on backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
> +    void createProject() throws Exception {
```
        CreateProjectResponse response = CreateProjectResponse.builder()
                .projectId(project.getId())
                .build();

        Tag tag1 = Tag.builder().tech("Spring").build();
        Tag tag2 = Tag.builder().tech("Django").build();   
```
미사용 변수입니다!

2023-09-20 16:53 UTC, youKeon commented on backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
> +        mvc.perform(delete(baseUrl + "/{id}", id).principal(new TestingAuthenticationToken("testEmail", "testPassword")))
```
java.lang.IllegalArgumentException: urlTemplate not found. If you are using MockMvc did you use RestDocumentationRequestBuilders to build the request?
```
혹시 저만 언팔로우 테스트에서 위 에러 발생하나요?!

2023-09-21 05:50 UTC, kimhalin commented on backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
> +        mvc.perform(delete(baseUrl + "/{id}", id).principal(new TestingAuthenticationToken("testEmail", "testPassword")))
엇 저는 에러는 안 났어요!

2023-09-21 05:51 UTC, kimhalin commented on backend/src/test/java/com/graphy/backend/domain/project/service/ProjectServiceTest.java
> +        assertThat(result.getProjectName()).isEqualTo(project.getProjectName());
새로운 걸 배웠네요.. 수정해놓을게요!

2023-09-21 05:52 UTC, kimhalin commented on backend/src/test/java/com/graphy/backend/domain/follow/controller/FollowControllerTest.java
> +//    @Test
주석처리해놓은 건 일단 테스트 다 돌아가게 하기 위함이었고, 위에 작성한대로 시큐리티 관련해서 한 번 싹 갈아 엎어야 할 것 같아서 그거 되면 주석 풀어놓으려 했었어요!

2023-09-21 12:00 UTC, youKeon approved these changes

2023-09-21 12:43 UTC, merged